#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: branch
      default: main
      private: no
    - name: version
      default: '11.3.0'
      private: no
    - name: builddir
      default: './build'
      private: no
  vars:
      major: "{{ (version | split('.'))[0] }}"
      reference: 'https://raw.githubusercontent.com/ansible-community/ansible-build-data/{{branch}}/{{major}}/ansible-{{version}}.deps'
  tasks:
    - name: deal with dirty dirs
      when: builddir is exists and builddir is directory
      block:
        - pause:
            prompt: 'Build dir ({{builddir}}) already exists, should we wipe, continue or abort?'
          register: cleanup
          name: Previous build detected

        - file: path={{builddir}} state=absent
          when: "cleanup.user_input == 'wipe'"
          name: wipe previous build

        - fail: msg="Aborting as per user request"
          when: "cleanup.user_input == 'abort'"
          name: abort!

        - fail: msg="Aborting since user input was confusing:{{cleanup.user_input}}"
          when: cleanup.user_input not in ('wipe', 'continue')
          name: abort anyways!

    - name: setup build dir
      file: path={{builddir}} state=directory

    - set_fact: deps="{{lookup('url', reference, split_lines=false)}}"

    - name: generate galaxy.yml
      template: src=galaxy.yml.j2 dest={{builddir}}/galaxy.yml

    - name: build collection
      shell: ansible-galaxy collection build
      args:
        chdir: '{{builddir}}'

    - name: get tarball name
      find: paths={{builddir}} patterns='*tgz'
      register: tarballs
