#!/usr/bin/env ansible-playbook
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: branch
      default: main
      private: no
    - name: version
      default: '2.10'
      private: no
    - name: builddir
      default: './build'
      private: no
  vars:
      major: "{{ (version | split('.'))[0] }}"
      reference: 'https://raw.githubusercontent.com/ansible-community/ansible-build-data/{{branch}}/{{major}}/ansible-{{version}}.deps'
  tasks:
    - name: setup build dir
      file: path={{builddir}} state=directory

    - set_fact: deps="{{lookup('url', reference, split_lines=false)}}"

    - name: generate galaxy.yml
      template: src=galaxy.yml.j2 dest={{builddir}}/galaxy.yml

    - name: build collection
      shell: ansible-galaxy collection build
      args:
        chdir: '{{builddir}}'

    - name: get tarball name
      find: paths={{builddir}} patterns='*tgz'
      register: tarballs
